AUDIO_PATH = "tests/{0}-{1}.wav"
VOICE_BY_ANIEMORE = "voiceByAniemore"
VOICE_BY_GOOGLE_AND_RUBERT = "voiceByGoogleAndRubert"
TEXT_BY_RUBERT = "textByRubert"
MESSAGE = {"msg": "k"}
ANIEMORE_EMO_MULTI_PATH = "emotion_multiplier.txt"
OGG_2_WAV_INPUT = "python/ogg2wavInput/"
OGG_2_WAV_OUTPUT = "python/tests/"
BOT_TOKEN = "7499114365:AAHT1gYbDhR34EYYv7O9kre_w-fyYnMRe2k"